version: 2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1-node
        environment: # environment variables for primary container
          RAILS_ENV: test

    steps:
      - checkout

      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v16.9.1/node-v16.9.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v16.9.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Configure Bundler for v2+
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: install sqlite3 dependencies
          command: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: Database migration
          command: bundle exec rake db:migrate

      # Yarn
      - run:
          name: Yarn
          command: yarn install

      # Webpacker
      - run:
          name: Webpacker
          command: NODE_ENV=test bundle exec rails webpacker:compile

      # run tests!
      - run:
          name: run tests
          command: bundle exec rake test
